// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RekeszAppBackend.Data;

#nullable disable

namespace RekeszAppBackend.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260910233000_MultiUserAccounts")]
partial class MultiUserAccounts
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.27").HasAnnotation("Relational:MaxIdentifierLength", 64);
        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("RekeszAppBackend.Domain.EladasTetel", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
            b.Property<DateOnly>("Datum").HasColumnType("date");
            b.Property<bool>("Elvitte").HasColumnType("tinyint(1)");
            b.Property<bool>("Fizetve").HasColumnType("tinyint(1)");
            b.Property<DateTime>("Ido").HasColumnType("datetime(6)");
            b.Property<decimal?>("Egysegar").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
            b.Property<int>("HianyFizettDb").HasColumnType("int");
            b.Property<string>("Megjegyzes").HasColumnType("longtext");
            b.Property<int>("Mennyiseg").HasColumnType("int");
            b.Property<int>("NapiSorszam").HasColumnType("int");
            b.Property<int>("RekeszTipusId").HasColumnType("int");
            b.Property<int?>("UserId").HasColumnType("int");
            b.Property<int?>("VevoId").HasColumnType("int");
            b.Property<int>("VisszahozottDb").HasColumnType("int");
            b.Property<int>("ZoldsegId").HasColumnType("int");
            b.HasKey("Id"); b.HasIndex("Datum"); b.HasIndex("RekeszTipusId"); b.HasIndex("UserId"); b.HasIndex("VevoId"); b.HasIndex("ZoldsegId"); b.ToTable("EladasTetelek");
        });

        modelBuilder.Entity("RekeszAppBackend.Domain.FelvasarlasTetel", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("AdottRekeszDb").HasColumnType("int"); b.Property<int>("AthelyezveDb").HasColumnType("int"); b.Property<bool>("Athozott").HasColumnType("tinyint(1)"); b.Property<DateOnly>("Datum").HasColumnType("date"); b.Property<bool>("Fizetve").HasColumnType("tinyint(1)"); b.Property<int>("Helyszin").HasColumnType("int"); b.Property<DateTime>("Ido").HasColumnType("datetime(6)"); b.Property<decimal?>("Egysegar").HasPrecision(10, 2).HasColumnType("decimal(10,2)"); b.Property<string>("Megjegyzes").HasColumnType("longtext"); b.Property<int>("Mennyiseg").HasColumnType("int"); b.Property<int>("NapiSorszam").HasColumnType("int"); b.Property<int?>("PartnerId").HasColumnType("int"); b.Property<int>("RekeszTipusId").HasColumnType("int"); b.Property<bool>("SajatTermek").HasColumnType("tinyint(1)"); b.Property<int?>("UserId").HasColumnType("int"); b.Property<int>("ZoldsegId").HasColumnType("int"); b.HasKey("Id"); b.HasIndex("Datum"); b.HasIndex("PartnerId"); b.HasIndex("RekeszTipusId"); b.HasIndex("UserId"); b.HasIndex("ZoldsegId"); b.ToTable("FelvasarlasTetelek");
        });

        modelBuilder.Entity("RekeszAppBackend.Domain.Partner", b =>
        { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id")); b.Property<string>("Megjegyzes").HasColumnType("longtext"); b.Property<string>("Nev").HasColumnType("longtext"); b.Property<int?>("UserId").HasColumnType("int"); b.HasKey("Id"); b.HasIndex("UserId", "Nev").IsUnique(); b.ToTable("Partnerek"); });

        modelBuilder.Entity("RekeszAppBackend.Domain.RekeszTipus", b =>
        { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id")); b.Property<string>("Nev").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)"); b.Property<int?>("UserId").HasColumnType("int"); b.HasKey("Id"); b.HasIndex("UserId", "Nev").IsUnique(); b.ToTable("RekeszTipusok"); });

        modelBuilder.Entity("RekeszAppBackend.Domain.User", b =>
        { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id")); b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("varchar(320)"); b.Property<bool>("EmailVerified").HasColumnType("tinyint(1)"); b.Property<string>("JelszoHash").IsRequired().HasColumnType("longtext"); b.Property<int>("Role").HasColumnType("int"); b.Property<DateTime>("RegisteredAt").HasColumnType("datetime(6)"); b.Property<string>("AszfVerzio").IsRequired().HasColumnType("longtext"); b.Property<DateTime>("AszfElfogadvaAt").HasColumnType("datetime(6)"); b.Property<string>("VerificationTokenHash").HasColumnType("longtext"); b.Property<DateTime?>("VerificationTokenExpiresAt").HasColumnType("datetime(6)"); b.HasKey("Id"); b.HasIndex("Email").IsUnique(); b.ToTable("Users"); });

        modelBuilder.Entity("RekeszAppBackend.Domain.Vevo", b =>
        { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id")); b.Property<string>("Megjegyzes").HasColumnType("longtext"); b.Property<string>("Nev").HasColumnType("longtext"); b.Property<int?>("UserId").HasColumnType("int"); b.HasKey("Id"); b.HasIndex("UserId"); b.ToTable("Vevek"); });

        modelBuilder.Entity("RekeszAppBackend.Domain.Zoldseg", b =>
        { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id")); b.Property<int?>("AlapertelmezettRekeszTipusId").HasColumnType("int"); b.Property<string>("KepUrl").HasColumnType("longtext"); b.Property<string>("Nev").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)"); b.Property<int?>("UserId").HasColumnType("int"); b.HasKey("Id"); b.HasIndex("AlapertelmezettRekeszTipusId"); b.HasIndex("UserId", "Nev").IsUnique(); b.ToTable("Zoldsegek"); });

        modelBuilder.Entity("RekeszAppBackend.Domain.EladasTetel", b => { b.HasOne("RekeszAppBackend.Domain.RekeszTipus", "RekeszTipus").WithMany().HasForeignKey("RekeszTipusId").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.HasOne("RekeszAppBackend.Domain.Vevo", "Vevo").WithMany().HasForeignKey("VevoId").OnDelete(DeleteBehavior.Restrict); b.HasOne("RekeszAppBackend.Domain.Zoldseg", "Zoldseg").WithMany().HasForeignKey("ZoldsegId").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.HasOne("RekeszAppBackend.Domain.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict); b.Navigation("RekeszTipus"); b.Navigation("Vevo"); b.Navigation("Zoldseg"); });
        modelBuilder.Entity("RekeszAppBackend.Domain.FelvasarlasTetel", b => { b.HasOne("RekeszAppBackend.Domain.Partner", "Partner").WithMany().HasForeignKey("PartnerId").OnDelete(DeleteBehavior.Restrict); b.HasOne("RekeszAppBackend.Domain.RekeszTipus", "RekeszTipus").WithMany().HasForeignKey("RekeszTipusId").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.HasOne("RekeszAppBackend.Domain.Zoldseg", "Zoldseg").WithMany().HasForeignKey("ZoldsegId").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.HasOne("RekeszAppBackend.Domain.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict); b.Navigation("Partner"); b.Navigation("RekeszTipus"); b.Navigation("Zoldseg"); });
        modelBuilder.Entity("RekeszAppBackend.Domain.Partner", b => b.HasOne("RekeszAppBackend.Domain.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict));
        modelBuilder.Entity("RekeszAppBackend.Domain.Vevo", b => b.HasOne("RekeszAppBackend.Domain.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict));
        modelBuilder.Entity("RekeszAppBackend.Domain.RekeszTipus", b => b.HasOne("RekeszAppBackend.Domain.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict));
        modelBuilder.Entity("RekeszAppBackend.Domain.Zoldseg", b => { b.HasOne("RekeszAppBackend.Domain.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict); b.HasOne("RekeszAppBackend.Domain.RekeszTipus", "AlapertelmezettRekeszTipus").WithMany().HasForeignKey("AlapertelmezettRekeszTipusId").OnDelete(DeleteBehavior.Restrict); b.Navigation("AlapertelmezettRekeszTipus"); });
#pragma warning restore 612, 618
    }
}
